name: Deploy to develop server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
          sudo apt-get install -y unzip
          unzip -d $HOME gradle-8.1.1-bin.zip
          export PATH=$HOME/gradle-8.1.1/bin:$PATH

      - name: set application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML_DEVELOP }}" > src/main/resources/application.yml

      - name: Build and package
        run: gradle clean build

      - name: Deploy to EC2
        run: |
          sudo apt-get install -y openssh-client
          echo "${{ secrets.KEY_PAIR }}" | base64 --decode > key.pem
          chmod 400 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no -r build/libs/*.jar ubuntu@${{ secrets.EC2_IP }}:~/app
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'bash -s' < ~/app/deploy.sh
